### ISSUE TITLE
Behavior change in buffer handling

### ISSUE THREAD

**Issue by tpetazzoni** [rjarzmik/rscope#10]
My typical emacs setup is to have the screen split vertically in two buffers, one to the left, one to the right.

In the previous rscope version I was using, when I was in the left buffer and did a 'C-c s d' to go to a symbol, it would open up the definition of that symbol in the same location: on the left hand-side of the screen.

With the latest version of rscope, when I do 'C-c s d' in the buffer opened on the left hand-side of the screen, it opens up the definition in a buffer located on the right hand-side of the screen. I find this behavior change annoying. Is there anyway to switch back to the previous behavior?

**Comment by rjarzmik** [comment]
Thomas Petazzoni <notifications@github.com> writes:

> My typical emacs setup is to have the screen split vertically in two buffers,
> one to the left, one to the right.
>
> In the previous rscope version I was using, when I was in the left buffer and
> did a 'C-c s d' to go to a symbol, it would open up the definition of that
> symbol in the same location: on the left hand-side of the screen.
>
> With the latest version of rscope, when I do 'C-c s d' in the buffer opened on
> the left hand-side of the screen, it opens up the definition in a buffer located
> on the right hand-side of the screen. I find this behavior change annoying. Is
> there anyway to switch back to the previous behavior?

Hi Thomas,

You're quite right, it's annoying.

Sylvain, I think it's your patch "Try reuse existing window to display result""
e4c0ec4 which triggered this regression, as the behavior disappears when I
revert it. Could you have a look please ?

Cheers.

-- 
Robert

**Comment by schouleu** [comment]
Hi,
Sorry for the delayed answer.

I've made a pull request here: https://github.com/rjarzmik/rscope/pull/13
However the behavior you are seeing is in fact the expected behavior in case of single result: display in other window.
So the fix is not really a fix but a change of the behavior in case of single result, it is now: display in same window.

The change will then affect other window configurations than only two windows, now even if you have a dozen of windows, the single result will be displayed in the window from where you called the search.

Regards,
Sylvain

**Comment by rjarzmik** [comment]
Thomas,

Could you try the "next" branch which holds Sylvain's change and tell me if the behavior is the one you expected ?
Sylvain, I tried the patch and the behavior looks correct wrt to my working methods.

Cheers.
Robert

**Comment by rjarzmik** [comment]
No answer from you, Thomas, I consider the issue closed in master branch.
